#############################################################################
# Makefile for building: GoogleTestDemo
# Generated by qmake (3.1) (Qt 5.13.1)
# Project:  GoogleTestDemo.pro
# Template: subdirs
# Command: C:\Qt\5.13.1\mingw73_64\bin\qmake.exe -o Makefile GoogleTestDemo.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = C:\Qt\5.13.1\mingw73_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\5.13.1\mingw73_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\5.13.1\mingw73_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-GUITests \
		sub-LogicalTests \
		sub-QtDemo


sub-GUITests-qmake_all:  FORCE
	@if not exist GUITests\ mkdir GUITests\ & if not exist GUITests\ exit 1
	cd GUITests\ && $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\GUITests\GUITests.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd GUITests\ && $(MAKE) -f Makefile qmake_all
sub-GUITests: FORCE
	@if not exist GUITests\ mkdir GUITests\ & if not exist GUITests\ exit 1
	cd GUITests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\GUITests\GUITests.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-GUITests-make_first: FORCE
	@if not exist GUITests\ mkdir GUITests\ & if not exist GUITests\ exit 1
	cd GUITests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\GUITests\GUITests.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-GUITests-all: FORCE
	@if not exist GUITests\ mkdir GUITests\ & if not exist GUITests\ exit 1
	cd GUITests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\GUITests\GUITests.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-GUITests-clean: FORCE
	@if not exist GUITests\ mkdir GUITests\ & if not exist GUITests\ exit 1
	cd GUITests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\GUITests\GUITests.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-GUITests-distclean: FORCE
	@if not exist GUITests\ mkdir GUITests\ & if not exist GUITests\ exit 1
	cd GUITests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\GUITests\GUITests.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-GUITests-install_subtargets: FORCE
	@if not exist GUITests\ mkdir GUITests\ & if not exist GUITests\ exit 1
	cd GUITests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\GUITests\GUITests.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-GUITests-uninstall_subtargets: FORCE
	@if not exist GUITests\ mkdir GUITests\ & if not exist GUITests\ exit 1
	cd GUITests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\GUITests\GUITests.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-LogicalTests-qmake_all:  FORCE
	@if not exist LogicalTests\ mkdir LogicalTests\ & if not exist LogicalTests\ exit 1
	cd LogicalTests\ && $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\LogicalTests\LogicalTests.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd LogicalTests\ && $(MAKE) -f Makefile qmake_all
sub-LogicalTests: FORCE
	@if not exist LogicalTests\ mkdir LogicalTests\ & if not exist LogicalTests\ exit 1
	cd LogicalTests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\LogicalTests\LogicalTests.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-LogicalTests-make_first: FORCE
	@if not exist LogicalTests\ mkdir LogicalTests\ & if not exist LogicalTests\ exit 1
	cd LogicalTests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\LogicalTests\LogicalTests.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-LogicalTests-all: FORCE
	@if not exist LogicalTests\ mkdir LogicalTests\ & if not exist LogicalTests\ exit 1
	cd LogicalTests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\LogicalTests\LogicalTests.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-LogicalTests-clean: FORCE
	@if not exist LogicalTests\ mkdir LogicalTests\ & if not exist LogicalTests\ exit 1
	cd LogicalTests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\LogicalTests\LogicalTests.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-LogicalTests-distclean: FORCE
	@if not exist LogicalTests\ mkdir LogicalTests\ & if not exist LogicalTests\ exit 1
	cd LogicalTests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\LogicalTests\LogicalTests.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-LogicalTests-install_subtargets: FORCE
	@if not exist LogicalTests\ mkdir LogicalTests\ & if not exist LogicalTests\ exit 1
	cd LogicalTests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\LogicalTests\LogicalTests.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-LogicalTests-uninstall_subtargets: FORCE
	@if not exist LogicalTests\ mkdir LogicalTests\ & if not exist LogicalTests\ exit 1
	cd LogicalTests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\LogicalTests\LogicalTests.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-QtDemo-qmake_all:  FORCE
	@if not exist QtDemo\ mkdir QtDemo\ & if not exist QtDemo\ exit 1
	cd QtDemo\ && $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\QtDemo\QtDemo.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd QtDemo\ && $(MAKE) -f Makefile qmake_all
sub-QtDemo: FORCE
	@if not exist QtDemo\ mkdir QtDemo\ & if not exist QtDemo\ exit 1
	cd QtDemo\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\QtDemo\QtDemo.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-QtDemo-make_first: FORCE
	@if not exist QtDemo\ mkdir QtDemo\ & if not exist QtDemo\ exit 1
	cd QtDemo\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\QtDemo\QtDemo.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-QtDemo-all: FORCE
	@if not exist QtDemo\ mkdir QtDemo\ & if not exist QtDemo\ exit 1
	cd QtDemo\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\QtDemo\QtDemo.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-QtDemo-clean: FORCE
	@if not exist QtDemo\ mkdir QtDemo\ & if not exist QtDemo\ exit 1
	cd QtDemo\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\QtDemo\QtDemo.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-QtDemo-distclean: FORCE
	@if not exist QtDemo\ mkdir QtDemo\ & if not exist QtDemo\ exit 1
	cd QtDemo\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\QtDemo\QtDemo.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-QtDemo-install_subtargets: FORCE
	@if not exist QtDemo\ mkdir QtDemo\ & if not exist QtDemo\ exit 1
	cd QtDemo\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\QtDemo\QtDemo.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-QtDemo-uninstall_subtargets: FORCE
	@if not exist QtDemo\ mkdir QtDemo\ & if not exist QtDemo\ exit 1
	cd QtDemo\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\QtDemo\QtDemo.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall

Makefile: GoogleTestDemo.pro C:/Qt/5.13.1/mingw73_64/mkspecs/win32-g++/qmake.conf C:/Qt/5.13.1/mingw73_64/mkspecs/features/spec_pre.prf \
		C:/Qt/5.13.1/mingw73_64/mkspecs/qdevice.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/features/device_config.prf \
		C:/Qt/5.13.1/mingw73_64/mkspecs/common/sanitize.conf \
		C:/Qt/5.13.1/mingw73_64/mkspecs/common/gcc-base.conf \
		C:/Qt/5.13.1/mingw73_64/mkspecs/common/g++-base.conf \
		C:/Qt/5.13.1/mingw73_64/mkspecs/common/angle.conf \
		C:/Qt/5.13.1/mingw73_64/mkspecs/features/win32/windows_vulkan_sdk.prf \
		C:/Qt/5.13.1/mingw73_64/mkspecs/common/windows-vulkan.conf \
		C:/Qt/5.13.1/mingw73_64/mkspecs/common/g++-win32.conf \
		C:/Qt/5.13.1/mingw73_64/mkspecs/common/windows-desktop.conf \
		C:/Qt/5.13.1/mingw73_64/mkspecs/qconfig.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3danimation.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dcore.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dextras.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dinput.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dlogic.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dquick.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3drender.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3drender_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_axbase.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_axbase_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_axcontainer.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_axcontainer_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_axserver.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_axserver_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_bluetooth.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_charts.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_charts_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_concurrent.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_core.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_core_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_datavisualization.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_dbus.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_dbus_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_designer.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_designer_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_gamepad.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_gui.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_gui_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_help.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_help_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_location.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_location_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_multimedia.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_network.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_network_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_networkauth.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_nfc.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_nfc_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_opengl.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_opengl_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_openglextensions.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_positioning.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_positioning_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_positioningquick.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_printsupport.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_qml.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_qml_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_qmltest.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_quick.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_quick_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_repparser.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_repparser_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_scxml.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_scxml_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_sensors.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_sensors_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_serialbus.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_serialport.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_serialport_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_sql.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_sql_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_svg.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_svg_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_testlib.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_testlib_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_texttospeech.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_uiplugin.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_uitools.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_uitools_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_webchannel.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_websockets.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_websockets_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_widgets.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_widgets_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_winextras.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_winextras_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_xml.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_xml_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		C:/Qt/5.13.1/mingw73_64/mkspecs/features/qt_functions.prf \
		C:/Qt/5.13.1/mingw73_64/mkspecs/features/qt_config.prf \
		C:/Qt/5.13.1/mingw73_64/mkspecs/win32-g++/qmake.conf \
		C:/Qt/5.13.1/mingw73_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		C:/Qt/5.13.1/mingw73_64/mkspecs/features/exclusive_builds.prf \
		C:/Qt/5.13.1/mingw73_64/mkspecs/features/toolchain.prf \
		C:/Qt/5.13.1/mingw73_64/mkspecs/features/default_pre.prf \
		C:/Qt/5.13.1/mingw73_64/mkspecs/features/win32/default_pre.prf \
		C:/Qt/5.13.1/mingw73_64/mkspecs/features/resolve_config.prf \
		C:/Qt/5.13.1/mingw73_64/mkspecs/features/exclusive_builds_post.prf \
		C:/Qt/5.13.1/mingw73_64/mkspecs/features/default_post.prf \
		C:/Qt/5.13.1/mingw73_64/mkspecs/features/qml_debug.prf \
		C:/Qt/5.13.1/mingw73_64/mkspecs/features/precompile_header.prf \
		C:/Qt/5.13.1/mingw73_64/mkspecs/features/warn_on.prf \
		C:/Qt/5.13.1/mingw73_64/mkspecs/features/qmake_use.prf \
		C:/Qt/5.13.1/mingw73_64/mkspecs/features/file_copies.prf \
		C:/Qt/5.13.1/mingw73_64/mkspecs/features/win32/windows.prf \
		C:/Qt/5.13.1/mingw73_64/mkspecs/features/testcase_targets.prf \
		C:/Qt/5.13.1/mingw73_64/mkspecs/features/exceptions.prf \
		C:/Qt/5.13.1/mingw73_64/mkspecs/features/yacc.prf \
		C:/Qt/5.13.1/mingw73_64/mkspecs/features/lex.prf \
		GoogleTestDemo.pro
	$(QMAKE) -o Makefile GoogleTestDemo.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
C:/Qt/5.13.1/mingw73_64/mkspecs/features/spec_pre.prf:
C:/Qt/5.13.1/mingw73_64/mkspecs/qdevice.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/features/device_config.prf:
C:/Qt/5.13.1/mingw73_64/mkspecs/common/sanitize.conf:
C:/Qt/5.13.1/mingw73_64/mkspecs/common/gcc-base.conf:
C:/Qt/5.13.1/mingw73_64/mkspecs/common/g++-base.conf:
C:/Qt/5.13.1/mingw73_64/mkspecs/common/angle.conf:
C:/Qt/5.13.1/mingw73_64/mkspecs/features/win32/windows_vulkan_sdk.prf:
C:/Qt/5.13.1/mingw73_64/mkspecs/common/windows-vulkan.conf:
C:/Qt/5.13.1/mingw73_64/mkspecs/common/g++-win32.conf:
C:/Qt/5.13.1/mingw73_64/mkspecs/common/windows-desktop.conf:
C:/Qt/5.13.1/mingw73_64/mkspecs/qconfig.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3danimation.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3danimation_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dcore.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dcore_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dextras.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dextras_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dinput.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dinput_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dlogic.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dquick.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dquick_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dquickextras.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dquickinput.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dquickrender.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3drender.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_3drender_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_axbase.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_axbase_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_axcontainer.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_axcontainer_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_axserver.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_axserver_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_bluetooth.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_charts.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_charts_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_concurrent.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_concurrent_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_core.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_core_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_datavisualization.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_dbus.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_dbus_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_designer.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_designer_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_edid_support_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_egl_support_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_fb_support_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_gamepad.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_gamepad_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_gui.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_gui_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_help.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_help_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_location.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_location_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_multimedia.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_multimedia_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_network.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_network_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_networkauth.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_networkauth_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_nfc.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_nfc_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_opengl.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_opengl_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_openglextensions.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_positioning.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_positioning_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_positioningquick.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_printsupport.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_printsupport_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_qml.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_qml_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_qmltest.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_qmltest_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_quick.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_quick_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_quickwidgets.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_remoteobjects.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_repparser.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_repparser_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_scxml.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_scxml_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_sensors.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_sensors_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_serialbus.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_serialbus_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_serialport.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_serialport_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_sql.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_sql_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_svg.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_svg_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_testlib.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_testlib_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_texttospeech.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_theme_support_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_uiplugin.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_uitools.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_uitools_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_webchannel.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_webchannel_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_websockets.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_websockets_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_widgets.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_widgets_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_winextras.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_winextras_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_xml.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_xml_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
C:/Qt/5.13.1/mingw73_64/mkspecs/features/qt_functions.prf:
C:/Qt/5.13.1/mingw73_64/mkspecs/features/qt_config.prf:
C:/Qt/5.13.1/mingw73_64/mkspecs/win32-g++/qmake.conf:
C:/Qt/5.13.1/mingw73_64/mkspecs/features/spec_post.prf:
.qmake.stash:
C:/Qt/5.13.1/mingw73_64/mkspecs/features/exclusive_builds.prf:
C:/Qt/5.13.1/mingw73_64/mkspecs/features/toolchain.prf:
C:/Qt/5.13.1/mingw73_64/mkspecs/features/default_pre.prf:
C:/Qt/5.13.1/mingw73_64/mkspecs/features/win32/default_pre.prf:
C:/Qt/5.13.1/mingw73_64/mkspecs/features/resolve_config.prf:
C:/Qt/5.13.1/mingw73_64/mkspecs/features/exclusive_builds_post.prf:
C:/Qt/5.13.1/mingw73_64/mkspecs/features/default_post.prf:
C:/Qt/5.13.1/mingw73_64/mkspecs/features/qml_debug.prf:
C:/Qt/5.13.1/mingw73_64/mkspecs/features/precompile_header.prf:
C:/Qt/5.13.1/mingw73_64/mkspecs/features/warn_on.prf:
C:/Qt/5.13.1/mingw73_64/mkspecs/features/qmake_use.prf:
C:/Qt/5.13.1/mingw73_64/mkspecs/features/file_copies.prf:
C:/Qt/5.13.1/mingw73_64/mkspecs/features/win32/windows.prf:
C:/Qt/5.13.1/mingw73_64/mkspecs/features/testcase_targets.prf:
C:/Qt/5.13.1/mingw73_64/mkspecs/features/exceptions.prf:
C:/Qt/5.13.1/mingw73_64/mkspecs/features/yacc.prf:
C:/Qt/5.13.1/mingw73_64/mkspecs/features/lex.prf:
GoogleTestDemo.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile GoogleTestDemo.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: sub-GUITests-qmake_all sub-LogicalTests-qmake_all sub-QtDemo-qmake_all FORCE

make_first: sub-GUITests-make_first sub-LogicalTests-make_first sub-QtDemo-make_first  FORCE
all: sub-GUITests-all sub-LogicalTests-all sub-QtDemo-all  FORCE
clean: sub-GUITests-clean sub-LogicalTests-clean sub-QtDemo-clean  FORCE
distclean: sub-GUITests-distclean sub-LogicalTests-distclean sub-QtDemo-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-GUITests-install_subtargets sub-LogicalTests-install_subtargets sub-QtDemo-install_subtargets FORCE
uninstall_subtargets: sub-GUITests-uninstall_subtargets sub-LogicalTests-uninstall_subtargets sub-QtDemo-uninstall_subtargets FORCE

sub-GUITests-debug:
	@if not exist GUITests\ mkdir GUITests\ & if not exist GUITests\ exit 1
	cd GUITests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\GUITests\GUITests.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-LogicalTests-debug:
	@if not exist LogicalTests\ mkdir LogicalTests\ & if not exist LogicalTests\ exit 1
	cd LogicalTests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\LogicalTests\LogicalTests.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-QtDemo-debug:
	@if not exist QtDemo\ mkdir QtDemo\ & if not exist QtDemo\ exit 1
	cd QtDemo\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\QtDemo\QtDemo.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
debug: sub-GUITests-debug sub-LogicalTests-debug sub-QtDemo-debug

sub-GUITests-release:
	@if not exist GUITests\ mkdir GUITests\ & if not exist GUITests\ exit 1
	cd GUITests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\GUITests\GUITests.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-LogicalTests-release:
	@if not exist LogicalTests\ mkdir LogicalTests\ & if not exist LogicalTests\ exit 1
	cd LogicalTests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\LogicalTests\LogicalTests.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-QtDemo-release:
	@if not exist QtDemo\ mkdir QtDemo\ & if not exist QtDemo\ exit 1
	cd QtDemo\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\QtDemo\QtDemo.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
release: sub-GUITests-release sub-LogicalTests-release sub-QtDemo-release

sub-GUITests-check:
	@if not exist GUITests\ mkdir GUITests\ & if not exist GUITests\ exit 1
	cd GUITests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\GUITests\GUITests.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-LogicalTests-check:
	@if not exist LogicalTests\ mkdir LogicalTests\ & if not exist LogicalTests\ exit 1
	cd LogicalTests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\LogicalTests\LogicalTests.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-QtDemo-check:
	@if not exist QtDemo\ mkdir QtDemo\ & if not exist QtDemo\ exit 1
	cd QtDemo\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\QtDemo\QtDemo.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
check: sub-GUITests-check sub-LogicalTests-check sub-QtDemo-check

sub-GUITests-benchmark:
	@if not exist GUITests\ mkdir GUITests\ & if not exist GUITests\ exit 1
	cd GUITests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\GUITests\GUITests.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-LogicalTests-benchmark:
	@if not exist LogicalTests\ mkdir LogicalTests\ & if not exist LogicalTests\ exit 1
	cd LogicalTests\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\LogicalTests\LogicalTests.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-QtDemo-benchmark:
	@if not exist QtDemo\ mkdir QtDemo\ & if not exist QtDemo\ exit 1
	cd QtDemo\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\zaufa\Documents\Qt Projects\GoogleTestDemo\QtDemo\QtDemo.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-GUITests-benchmark sub-LogicalTests-benchmark sub-QtDemo-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

